export const JAYPIE = {
  ENV: {
    DATADOG_API_KEY: "DATADOG_API_KEY",
    DD_SITE: "DD_SITE",
    LOG_LEVEL: "LOG_LEVEL",
    MODULE_LOG_LEVEL: "MODULE_LOG_LEVEL",
    PROJECT_CHAOS: "PROJECT_CHAOS",
    PROJECT_ENV: "PROJECT_ENV",
    PROJECT_KEY: "PROJECT_KEY",
    PROJECT_SEED: "PROJECT_SEED",
    PROJECT_SERVICE: "PROJECT_SERVICE",
    PROJECT_SPONSOR: "PROJECT_SPONSOR",
    PROJECT_VERSION: "PROJECT_VERSION",
    SECRET_DATADOG_API_KEY: "SECRET_DATADOG_API_KEY",
  },
  LIB: {
    AWS: "@jaypie/aws",
    CDK: "@jaypie/cdk",
    CONSTRUCTS: "@jaypie/constructs",
    CORE: "@jaypie/core",
    ERRORS: "@jaypie/errors",
    ESLINT: "@jaypie/eslint",
    EXPRESS: "@jaypie/express",
    FABRICATOR: "@jaypie/fabricator",
    JAYPIE: "jaypie",
    KIT: "@jaypie/kit",
    LAMBDA: "@jaypie/lambda",
    LOGGER: "@jaypie/logger",
    LLM: "@jaypie/llm",
    MATCHERS: "@jaypie/matchers",
    MCP: "@jaypie/mcp",
    MOCK: "@jaypie/mock",
    MONGOOSE: "@jaypie/mongoose",
    TESTKIT: "@jaypie/testkit",
    TEXTTRACT: "@jaypie/textract",
    TYPES: "@jaypie/types",
    WEBKIT: "@jaypie/webkit",
  },
  LAYER: {
    EXPRESS: "express",
    HANDLER: "handler",
    JAYPIE: "jaypie",
    LAMBDA: "lambda",
    MODULE: "module",
    NEXTJS: "nextjs",
  },
  LOGGER: {
    DEFAULT: "default",
    MODULE: "module",
  },
  UNKNOWN: "unknown",
};

export const PROJECT = {
  SPONSOR: {
    FINLAYSON: "finlaysonstudio",
    JAYPIE: "jaypie",
    KNOWDEV: "knowdev.studio",
  },
};
